name: CI

on: 
  [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Checkout current repository (repository yang menjalankan workflow ini)
    - name: Checkout Current Repository
      uses: actions/checkout@v3

    # Clone repository lain
    - name: Clone auto-coursera repository
      run: |
        git clone https://github.com/fikriarmiafahmi/auto-coursera.git
        cd auto-coursera
        dir

    # Install Ngrok (opsional, sesuai dengan kebutuhan Anda)
    - name: Download Ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract Ngrok
      run: Expand-Archive ngrok.zip
    - name: Auth Ngrok
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    # Enable Remote Desktop
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    # Install Git
    - name: Install Git
      shell: cmd
      run: choco install git -y

    # Install Python 3.10
    - name: Install Python 3.10
      shell: cmd
      run: |
        choco install python --version=3.10 -y
        refreshenv

    # Install Python modules
    - name: Install Python Modules
      shell: cmd
      run: |
        python -m pip install selenium webdriver-manager pyautogui keyboard

    # (Opsional) Install Visual Studio Code
    - name: Install Visual Studio Code
      run: |
        choco install vscode -y

    # Start Ngrok Tunnel
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
